-- Some names that do not map to item names were mapped using:
-- https://github.com/SteamDatabase/GameTracking-Dota2/blob/master/game/dota/pak01_dir/scripts/npc/items.txt

-- Item dependencies as well as shop locations were resolved using https://dota2.gamepedia.com/Items

items = {
	{name="item_abyssal_blade", components={"item_basher", "item_vanguard", "item_recipe_abyssal_blade"}, shop="base"},
	{name="item_aegis", components={}, shop="base"},
	{name="item_aether_lens", components={"item_void_stone", "item_recipe_aether_lens", "item_energy_booster"}, shop="base"},
	{name="item_ancient_janggo", components={"item_recipe_ancient_janggo", "item_bracer", "item_sobi_mask", "item_wind_lace"}, shop="base"},
	{name="item_arcane_boots", components={"item_energy_booster","item_boots"}, shop="base"},
	{name="item_armlet", components={"item_recipe_armlet", "item_gloves", "item_blades_of_attack", "item_helm_of_iron_will"}, shop="base"},
	{name="item_assault", components={"item_recipe_assault", "item_hyperstone", "item_platemail", "item_chainmail"}, shop="base"},
	{name="item_banana", components={}, shop="base"},
	{name="item_basher", components={"item_recipe_basher", "item_belt_of_strength", "item_javelin"}, shop="baseside"},
	{name="item_belt_of_strength", components={}, shop="base"},
	{name="item_bfury", components={"item_pers", "item_demon_edge", "item_quelling_blade"}, shop="base"},
	{name="item_black_king_bar", components={"item_recipe_black_king_bar", "item_ogre_axe", "item_mithril_hammer"}, shop="base"},
	{name="item_blade_mail", components={"item_robe", "item_chainmail", "item_broadsword"}, shop="base"},
	{name="item_blade_of_alacrity", components={}, shop="base"},
	{name="item_blades_of_attack", components={}, shop="base"},
	{name="item_blight_stone", components={}, shop="base"},
	{name="item_blink", components={}, shop="baseside"},
	{name="item_bloodstone", components={"item_soul_booster", "item_pers"}, shop="base"},
	{name="item_bloodthorn", components={"item_lesser_crit", "item_recipe_bloodthorn", "item_orchid"}, shop="base"},
	{name="item_boots", components={}, shop="baseside"},
	{name="item_boots_of_elves", components={}, shop="baseside"},
	{name="item_bottle", components={}, shop="base"},
	{name="item_bracer", components={"item_circlet", "item_gauntlets", "item_recipe_bracer"}, shop="base"},
	{name="item_branches", components={}, shop="base"},
	{name="item_broadsword", components={}, shop="baseside"},
	{name="item_buckler", components={"item_recipe_buckler", "item_branches", "item_chainmail"}, shop="base"},
	{name="item_butterfly", components={"item_eagle", "item_quarterstaff", "item_talisman_of_evasion"}, shop="base"},
	{name="item_chainmail", components={}, shop="baseside"},
	{name="item_cheese", components={}, shop="base"},
	{name="item_circlet", components={}, shop="base"},
	{name="item_clarity", components={}, shop="base"},
	{name="item_claymore", components={}, shop="base"},
	{name="item_cloak", components={}, shop="baseside"},
	{name="item_courier", components={}, shop="base"},
	{name="item_crimson_guard", components={"item_recipe_crimson_guard", "item_vanguard", "item_buckler"}, shop="base"},
	{name="item_cyclone", components={"item_recipe_cyclone", "item_void_stone","item_staff_of_wizardry", "item_wind_lace"}, shop="base"},
	{name="item_dagon", components={"item_recipe_dagon", "item_null_talisman", "item_staff_of_wizardry"}, shop="base"},
	{name="item_dagon_2", components={"item_dagon", "item_recipe_dagon"}, shop="base"},
	{name="item_dagon_3", components={"item_dagon_2", "item_recipe_dagon"}, shop="base"},
	{name="item_dagon_4", components={"item_dagon_3", "item_recipe_dagon"}, shop="base"},
	{name="item_dagon_5", components={"item_dagon_4"}, shop="base"},
	{name="item_demon_edge", components={}, shop="secret"},
	{name="item_desolator", components={"item_mithril_hammer", "item_blight_stone"}, shop="base"},
	{name="item_diffusal_blade", components={"item_recipe_diffusal_blade", "item_robe", "item_blade_of_alacrity", "item_blade_of_alacrity"}, shop="base"},
	{name="item_diffusal_blade_2", components={"item_diffusal_blade", "item_recipe_diffusal_blade"}, shop="base"},
	{name="item_dragon_lance", components={"item_boots_of_elves", "item_boots_of_elves", "item_ogre_axe"}, shop="base"},
	{name="item_dust", components={}, shop="base"},
	{name="item_eagle", components={}, shop="secret"},
	{name="item_echo_sabre", components={"item_oblivion_staff", "item_ogre_axe"}, shop="base"},
	{name="item_enchanted_mango", components={}, shop="base"},
	{name="item_energy_booster", components={}, shop="sidesecret"},
	{name="item_ethereal_blade", components={"item_eagle", "item_ghost"}, shop="base"},
	{name="item_faerie_fire", components={}, shop="base"},
	{name="item_flask", components={}, shop="base"},
	{name="item_flying_courier", components={}, shop="base"},
	{name="item_force_staff", components={"item_recipe_force_staff", "item_staff_of_wizardry", "item_ring_of_health"}, shop="base"},
	{name="item_gauntlets", components={}, shop="base"},
	{name="item_gem", components={}, shop="base"},
	{name="item_ghost", components={}, shop="base"},
	{name="item_glimmer_cape", components={"item_shadow_amulet","item_cloak"}, shop="base"},
	{name="item_gloves", components={}, shop="baseside"},
	{name="item_greater_crit", components={"item_recipe_greater_crit", "item_lesser_crit", "item_demon_edge"}, shop="base"},
	{name="item_greevil_whistle", components={}, shop="base"},
	{name="item_greevil_whistle_toggle", components={}, shop="base"},
	{name="item_guardian_greaves", components={"item_recipe_guardian_greaves", "item_mekansm", "item_arcane_boots"}, shop="base"},
	{name="item_halloween_candy_corn", components={}, shop="base"},
	{name="item_halloween_rapier", components={}, shop="base"},
	{name="item_hand_of_midas", components={"item_gloves", "item_recipe_hand_of_midas"}, shop="base"},
	{name="item_headdress", components={"item_recipe_headdress", "item_branches", "item_ring_of_regen"}, shop="base"},
	{name="item_heart", components={"item_vitality_booster", "item_vitality_booster", "item_reaver"}, shop="base"},
	{name="item_heavens_halberd", components={"item_sange", "item_talisman_of_evasion"}, shop="base"},
	{name="item_helm_of_iron_will", components={}, shop="baseside"},
	{name="item_helm_of_the_dominator", components={"item_headdress", "item_gloves", "item_ring_of_health"}, shop="base"},
	{name="item_hood_of_defiance", components={"item_cloak", "item_ring_of_health", "item_ring_of_regen"}, shop="base"},
	{name="item_hurricane_pike", components={"item_dragon_lance", "item_force_staff", "item_wraith_band"}, shop="base"},
	{name="item_hyperstone", components={}, shop="secret"},
	{name="item_infused_raindrop", components={}, shop="base"},
	{name="item_invis_sword", components={"item_claymore", "item_shadow_amulet"}, shop="base"},
	{name="item_iron_talon", components={}, shop="base"},
	{name="item_javelin", components={}, shop="base"},
	{name="item_lesser_crit", components={"item_recipe_lesser_crit", "item_blades_of_attack", "item_broadsword"}, shop="base"},
	{name="item_lifesteal", components={}, shop="baseside"},
	{name="item_lotus_orb", components={"item_pers", "item_platemail", "item_energy_booster"}, shop="base"},
	{name="item_maelstrom", components={"item_recipe_maelstrom", "item_gloves", "item_mithril_hammer"}, shop="base"},
	{name="item_magic_stick", components={}, shop="baseside"},
	{name="item_magic_wand", components={"item_enchanted_mango", "item_branches", "item_branches", "item_magic_stick"}, shop="base"},
	{name="item_manta", components={"item_recipe_manta", "item_yasha", "item_ultimate_orb"}, shop="base"},
	{name="item_mantle", components={}, shop="base"},
	{name="item_mask_of_madness", components={"item_quarterstaff", "item_lifesteal"}, shop="base"},
	{name="item_medallion_of_courage", components={"item_chainmail", "item_blight_stone", "item_sobi_mask"}, shop="base"},
	{name="item_mekansm", components={"item_recipe_mekansm", "item_headdress", "item_buckler"}, shop="base"},
	{name="item_mithril_hammer", components={}, shop="base"},
	{name="item_mjollnir", components={"item_recipe_mjollnir", "item_maelstrom", "item_hyperstone"}, shop="base"},
	{name="item_monkey_king_bar", components={"item_hyperstone", "item_javelin", "item_javelin"}, shop="base"},
	{name="item_moon_shard", components={"item_hyperstone", "item_hyperstone"}, shop="base"},
	{name="item_mystery_arrow", components={}, shop="base"},
	{name="item_mystery_hook", components={}, shop="base"},
	{name="item_mystery_missile", components={}, shop="base"},
	{name="item_mystery_toss", components={}, shop="base"},
	{name="item_mystery_vacuum", components={}, shop="base"},
	{name="item_mystic_staff", components={}, shop="secret"},
	{name="item_necronomicon", components={"item_recipe_necronomicon", "item_sobi_mask", "item_belt_of_strength"}, shop="base"},
	{name="item_necronomicon_2", components={"item_necronomicon", "item_recipe_necronomicon"}, shop="base"},
	{name="item_necronomicon_3", components={"item_necronomicon_2", "item_recipe_necronomicon"}, shop="base"},
	{name="item_null_talisman", components={"item_recipe_null_talisman", "item_mantle", "item_circlet"}, shop="base"},
	{name="item_oblivion_staff", components={"item_robe", "item_quarterstaff", "item_sobi_mask"}, shop="base"},
	{name="item_octarine_core", components={"item_soul_booster", "item_mystic_staff"}, shop="base"},
	{name="item_ogre_axe", components={}, shop="base"},
	{name="item_orb_of_venom", components={}, shop="base"},
	{name="item_orchid", components={"item_recipe_orchid", "item_oblivion_staff", "item_oblivion_staff"}, shop="base"},
	{name="item_pers", components={"item_void_stone", "item_ring_of_health"}, shop="base"},
	{name="item_phase_boots", components={"item_blades_of_attack", "item_blades_of_attack", "item_boots"}, shop="base"},
	{name="item_pipe", components={"item_recipe_pipe", "item_hood_of_defiance", "item_headdress", }, shop="base"},
	{name="item_platemail", components={}, shop="secret"},
	{name="item_point_booster", components={}, shop="secret"},
	{name="item_poor_mans_shield", components={}, shop="base"},
	{name="item_power_treads", components={"item_gloves","item_boots_of_elves", "item_belt_of_strength"}, shop="base"},
	{name="item_present", components={}, shop="base"},
	{name="item_quarterstaff", components={}, shop="base"},
	{name="item_quelling_blade", components={}, shop="baseside"},
	{name="item_radiance", components={"item_recipe_radiance", "item_relic"}, shop="base"},
	{name="item_rapier", components={"item_relic", "item_demon_edge"}, shop="base"},
	{name="item_reaver", components={}, shop="secret"},
	{name="item_recipe_abyssal_blade", components={}, shop="base"},
	{name="item_recipe_aether_lens", components={}, shop="base"},
	{name="item_recipe_ancient_janggo", components={}, shop="base"},
	{name="item_recipe_arcane_boots", components={}, shop="base"},
	{name="item_recipe_armlet", components={}, shop="base"},
	{name="item_recipe_assault", components={}, shop="base"},
	{name="item_recipe_basher", components={}, shop="base"},
	{name="item_recipe_bfury", components={}, shop="base"},
	{name="item_recipe_black_king_bar", components={}, shop="base"},
	{name="item_recipe_blade_mail", components={}, shop="base"},
	{name="item_recipe_bloodstone", components={}, shop="base"},
	{name="item_recipe_bloodthorn", components={}, shop="base"},
	{name="item_recipe_bracer", components={}, shop="base"},
	{name="item_recipe_buckler", components={}, shop="base"},
	{name="item_recipe_butterfly", components={}, shop="base"},
	{name="item_recipe_crimson_guard", components={}, shop="base"},
	{name="item_recipe_cyclone", components={}, shop="base"},
	{name="item_recipe_dagon", components={}, shop="base"},
	{name="item_recipe_dagon_2", components={}, shop="base"},
	{name="item_recipe_dagon_3", components={}, shop="base"},
	{name="item_recipe_dagon_4", components={}, shop="base"},
	{name="item_recipe_dagon_5", components={}, shop="base"},
	{name="item_recipe_desolator", components={}, shop="base"},
	{name="item_recipe_diffusal_blade", components={}, shop="base"},
	{name="item_recipe_diffusal_blade_2", components={}, shop="base"},
	{name="item_recipe_dragon_lance", components={}, shop="base"},
	{name="item_recipe_echo_sabre", components={}, shop="base"},
	{name="item_recipe_ethereal_blade", components={}, shop="base"},
	{name="item_recipe_force_staff", components={}, shop="base"},
	{name="item_recipe_glimmer_cape", components={}, shop="base"},
	{name="item_recipe_greater_crit", components={}, shop="base"},
	{name="item_recipe_guardian_greaves", components={}, shop="base"},
	{name="item_recipe_hand_of_midas", components={}, shop="base"},
	{name="item_recipe_headdress", components={}, shop="base"},
	{name="item_recipe_heart", components={}, shop="base"},
	{name="item_recipe_heavens_halberd", components={}, shop="base"},
	{name="item_recipe_helm_of_the_dominator", components={}, shop="base"},
	{name="item_recipe_hood_of_defiance", components={}, shop="base"},
	{name="item_recipe_hurricane_pike", components={}, shop="base"},
	{name="item_recipe_invis_sword", components={}, shop="base"},
	{name="item_recipe_iron_talon", components={}, shop="base"},
	{name="item_recipe_lesser_crit", components={}, shop="base"},
	{name="item_recipe_lotus_orb", components={}, shop="base"},
	{name="item_recipe_maelstrom", components={}, shop="base"},
	{name="item_recipe_magic_wand", components={}, shop="base"},
	{name="item_recipe_manta", components={}, shop="base"},
	{name="item_recipe_mask_of_madness", components={}, shop="base"},
	{name="item_recipe_medallion_of_courage", components={}, shop="base"},
	{name="item_recipe_mekansm", components={}, shop="base"},
	{name="item_recipe_mjollnir", components={}, shop="base"},
	{name="item_recipe_monkey_king_bar", components={}, shop="base"},
	{name="item_recipe_moon_shard", components={}, shop="base"},
	{name="item_recipe_necronomicon", components={}, shop="base"},
	{name="item_recipe_necronomicon_2", components={}, shop="base"},
	{name="item_recipe_necronomicon_3", components={}, shop="base"},
	{name="item_recipe_null_talisman", components={}, shop="base"},
	{name="item_recipe_oblivion_staff", components={}, shop="base"},
	{name="item_recipe_octarine_core", components={}, shop="base"},
	{name="item_recipe_orchid", components={}, shop="base"},
	{name="item_recipe_pers", components={}, shop="base"},
	{name="item_recipe_phase_boots", components={}, shop="base"},
	{name="item_recipe_pipe", components={}, shop="base"},
	{name="item_recipe_poor_mans_shield", components={}, shop="base"},
	{name="item_recipe_power_treads", components={}, shop="base"},
	{name="item_recipe_radiance", components={}, shop="base"},
	{name="item_recipe_rapier", components={}, shop="base"},
	{name="item_recipe_refresher", components={}, shop="base"},
	{name="item_recipe_ring_of_aquila", components={}, shop="base"},
	{name="item_recipe_ring_of_basilius", components={}, shop="base"},
	{name="item_recipe_rod_of_atos", components={}, shop="base"},
	{name="item_recipe_sange", components={}, shop="base"},
	{name="item_recipe_sange_and_yasha", components={}, shop="base"},
	{name="item_recipe_satanic", components={}, shop="base"},
	{name="item_recipe_sheepstick", components={}, shop="base"},
	{name="item_recipe_shivas_guard", components={}, shop="base"},
	{name="item_recipe_silver_edge", components={}, shop="base"},
	{name="item_recipe_skadi", components={}, shop="base"},
	{name="item_recipe_solar_crest", components={}, shop="base"},
	{name="item_recipe_soul_booster", components={}, shop="base"},
	{name="item_recipe_soul_ring", components={}, shop="base"},
	{name="item_recipe_sphere", components={}, shop="base"},
	{name="item_recipe_tranquil_boots", components={}, shop="base"},
	{name="item_recipe_travel_boots", components={}, shop="base"},
	{name="item_recipe_travel_boots_2", components={}, shop="base"},
	{name="item_recipe_ultimate_scepter", components={}, shop="base"},
	{name="item_recipe_urn_of_shadows", components={}, shop="base"},
	{name="item_recipe_vanguard", components={}, shop="base"},
	{name="item_recipe_veil_of_discord", components={}, shop="base"},
	{name="item_recipe_vladmir", components={}, shop="base"},
	{name="item_recipe_ward_dispenser", components={}, shop="base"},
	{name="item_recipe_wraith_band", components={}, shop="base"},
	{name="item_recipe_yasha", components={}, shop="base"},
	{name="item_refresher", components={"item_recipe_refresher", "item_pers", "item_pers"}, shop="base"},
	{name="item_relic", components={}, shop="secret"},
	{name="item_ring_of_aquila", components={"item_ring_of_basilius", "item_wraith_band"}, shop="base"},
	{name="item_ring_of_basilius", components={"item_ring_of_protection", "item_sobi_mask"}, shop="base"},
	{name="item_ring_of_health", components={}, shop="base"},
	{name="item_ring_of_protection", components={}, shop="baseside"},
	{name="item_ring_of_regen", components={}, shop="base"},
	{name="item_river_painter", components={}, shop="base"},
	{name="item_river_painter2", components={}, shop="base"},
	{name="item_river_painter3", components={}, shop="base"},
	{name="item_river_painter4", components={}, shop="base"},
	{name="item_river_painter5", components={}, shop="base"},
	{name="item_river_painter6", components={}, shop="base"},
	{name="item_river_painter7", components={}, shop="base"},
	{name="item_robe", components={}, shop="baseside"},
	{name="item_rod_of_atos", components={"item_recipe_rod_of_atos", "item_bracer", "item_bracer", "item_staff_of_wizardry"}, shop="base"},
	{name="item_sange", components={"item_recipe_sange", "item_ogre_axe", "item_belt_of_strength"}, shop="base"},
	{name="item_sange_and_yasha", components={"item_yasha", "item_sange"}, shop="base"},
	{name="item_satanic", components={"item_reaver", "item_claymore", "item_lifesteal"}, shop="base"},
	{name="item_shadow_amulet", components={}, shop="base"},
	{name="item_sheepstick", components={"item_mystic_staff", "item_ultimate_orb", "item_void_stone"}, shop="base"},
	{name="item_shivas_guard", components={"item_recipe_shivas_guard", "item_mystic_staff", "item_platemail"}, shop="base"},
	{name="item_silver_edge", components={"item_recipe_silver_edge", "item_invis_sword", "item_ultimate_orb"}, shop="base"},
	{name="item_skadi", components={"item_point_booster", "item_ultimate_orb", "item_ultimate_orb"}, shop="base"},
	{name="item_slippers", components={}, shop="base"},
	{name="item_smoke_of_deceit", components={}, shop="base"},
	{name="item_sobi_mask", components={}, shop="base"},
	{name="item_solar_crest", components={"item_medallion_of_courage", "item_talisman_of_evasion"}, shop="base"},
	{name="item_soul_booster", components={"item_point_booster", "item_vitality_booster", "item_energy_booster"}, shop="base"},
	{name="item_soul_ring", components={"item_recipe_soul_ring", "item_gauntlets", "item_ring_of_regen", "item_gauntlets"}, shop="base"},
	{name="item_sphere", components={"item_recipe_sphere", "item_pers", "item_ultimate_orb"}, shop="base"},
	{name="item_staff_of_wizardry", components={}, shop="base"},
	{name="item_stout_shield", components={}, shop="base"},
	{name="item_talisman_of_evasion", components={}, shop="secret"},
	{name="item_tango", components={}, shop="base"},
	{name="item_tango_single", components={}, shop="base"},
	{name="item_tome_of_knowledge", components={}, shop="base"},
	{name="item_tpscroll", components={}, shop="baseside"},
	{name="item_tranquil_boots", components={"item_wind_lace", "item_boots", "item_ring_of_regen"}, shop="base"},
	{name="item_travel_boots", components={"item_boots", "item_recipe_travel_boots"}, shop="base"},
	{name="item_travel_boots_2", components={"item_travel_boots", "item_recipe_travel_boots"}, shop="base"},
	{name="item_ultimate_orb", components={}, shop="secret"},
	{name="item_ultimate_scepter", components={"item_point_booster", "item_ogre_axe", "item_blade_of_alacrity", "item_staff_of_wizardry"}, shop="base"},
	{name="item_urn_of_shadows", components={"item_recipe_urn_of_shadows", "item_infused_raindrop", "item_circlet", "item_ring_of_protection"}, shop="base"},
	{name="item_vanguard", components={"item_vitality_booster", "item_stout_shield", "item_ring_of_health"}, shop="base"},
	{name="item_veil_of_discord", components={ "item_recipe_veil_of_discord", "item_null_talisman", "item_null_talisman", "item_helm_of_iron_will"}, shop="base"},
	{name="item_vitality_booster", components={}, shop="sidesecret"},
	{name="item_vladmir", components={"item_headdress", "item_ring_of_basilius", "item_lifesteal"}, shop="base"},
	{name="item_void_stone", components={}, shop="baseside"},
	{name="item_ward_dispenser", components={}, shop="base"},
	{name="item_ward_observer", components={}, shop="base"},
	{name="item_ward_sentry", components={}, shop="base"},
	{name="item_wind_lace", components={}, shop="base"},
	{name="item_winter_cake", components={}, shop="base"},
	{name="item_winter_coco", components={}, shop="base"},
	{name="item_winter_cookie", components={}, shop="base"},
	{name="item_winter_greevil_chewy", components={}, shop="base"},
	{name="item_winter_greevil_garbage", components={}, shop="base"},
	{name="item_winter_greevil_treat", components={}, shop="base"},
	{name="item_winter_ham", components={}, shop="base"},
	{name="item_winter_kringle", components={}, shop="base"},
	{name="item_winter_mushroom", components={}, shop="base"},
	{name="item_winter_skates", components={}, shop="base"},
	{name="item_winter_stocking", components={}, shop="base"},
	{name="item_wraith_band", components={"item_circlet", "item_recipe_wraith_band", "item_slippers"}, shop="base"},
	{name="item_yasha", components={"item_recipe_yasha", "item_blade_of_alacrity", "item_boots_of_elves"}, shop="base"},
	
	{name="item_kaya", components={"item_recipe_kaya", "item_robe", "item_staff_of_wizardry"}, shop="base"},
	{name="item_recipe_kaya", components={}, shop="base"},

	{name="item_meteor_hammer", components={"item_ring_of_regen", "item_staff_of_wizardry", "item_ogre_axe", "item_sobi_mask"}, shop="base"},
	{name="item_recipe_meteor_hammer", components={"item_staff_of_wizardry", "item_ogre_axe"}, shop="base"},

	{name="item_nullifier", components={"item_helm_of_iron_will", "item_relic"}, shop="base"},
	{name="item_recipe_nullifier", components={}, shop="base"},

	{name="item_spirit_vessel", components={"item_recipe_spirit_vessel", "item_urn_of_shadows", "item_vitality_booster", "item_wind_lace"}, shop="base"},
	{name="item_recipe_spirit_vessel", components={}, shop="base"},
	{name="item_aeon_disk", components={"item_recipe_aeon_disk", "item_vitality_booster", "item_energy_booster"}, shop="base"},
	{name="item_recipe_aeon_disk", components={}, shop="base"}
}
